"""adding thumbnail

Revision ID: 04feac0a5644
Revises: cee4fb940186
Create Date: 2025-12-26 12:43:10.864418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04feac0a5644'
down_revision = 'cee4fb940186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_thumbnail', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.drop_column('image_thumbnail')

    # ### end Alembic commands ###
