"""Rename cms_api_key to access_api_key and add new cms_api_key for downstream CMS

Revision ID: 10f8fbee029e
Revises: 5746e7c56f26
Create Date: 2025-12-01 08:45:01.911842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f8fbee029e'
down_revision = '5746e7c56f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_api_key', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('access_api_key')

    # ### end Alembic commands ###
