"""Add Sponsy integration fields

Revision ID: 1c9c8d06c10c
Revises: 4fc4c8941ac9
Create Date: 2026-03-11 11:03:55.957537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9c8d06c10c'
down_revision = '4fc4c8941ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsy_top_placement_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sponsy_mid_placement_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sponsy_mid_position', sa.Integer(), nullable=True))

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsy_api_key', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('sponsy_publication_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('sponsy_publication_id')
        batch_op.drop_column('sponsy_api_key')

    with op.batch_alter_table('newsletter_template', schema=None) as batch_op:
        batch_op.drop_column('sponsy_mid_position')
        batch_op.drop_column('sponsy_mid_placement_id')
        batch_op.drop_column('sponsy_top_placement_id')

    # ### end Alembic commands ###
