"""Add WeeklyBriefing model

Revision ID: 21478fb15e00
Revises: f5dc935706df
Create Date: 2026-04-10 12:29:09.658868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21478fb15e00'
down_revision = 'f5dc935706df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_briefing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_briefing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_briefing_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_briefing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_briefing_publication_id'))

    op.drop_table('weekly_briefing')
    # ### end Alembic commands ###
