"""add issue_date to newsletter

Revision ID: 291851e40cb0
Revises: 1c9c8d06c10c
Create Date: 2026-03-16 09:53:31.971235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291851e40cb0'
down_revision = '1c9c8d06c10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('issue_date')

    # ### end Alembic commands ###
