"""Add notification_emails to publication

Revision ID: 2a3ec0fcac5c
Revises: 63b783718775
Create Date: 2026-03-05 10:01:46.756222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3ec0fcac5c'
down_revision = '63b783718775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_emails', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('notification_emails')

    # ### end Alembic commands ###
