"""Add candidate content generation schedule fields

Revision ID: 2ea86efa18d9
Revises: e506ffefb5b6
Create Date: 2026-02-23 09:07:39.708034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea86efa18d9'
down_revision = 'e506ffefb5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_schedule_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('candidate_schedule_frequency', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('candidate_schedule_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('candidate_schedule_day_of_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_candidate_schedule_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_candidate_schedule_run', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_publication_next_candidate_schedule_run'), ['next_candidate_schedule_run'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_next_candidate_schedule_run'))
        batch_op.drop_column('next_candidate_schedule_run')
        batch_op.drop_column('last_candidate_schedule_run')
        batch_op.drop_column('candidate_schedule_day_of_week')
        batch_op.drop_column('candidate_schedule_time')
        batch_op.drop_column('candidate_schedule_frequency')
        batch_op.drop_column('candidate_schedule_enabled')

    # ### end Alembic commands ###
