"""Add ad block ID fields to newsletter templates

Revision ID: 2f1ce09bbcb6
Revises: 291851e40cb0
Create Date: 2026-03-16 14:14:28.854682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1ce09bbcb6'
down_revision = '291851e40cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsy_top_ad_block_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sponsy_mid_ad_block_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_template', schema=None) as batch_op:
        batch_op.drop_column('sponsy_mid_ad_block_id')
        batch_op.drop_column('sponsy_top_ad_block_id')

    # ### end Alembic commands ###
