"""Add industry_description to Publication

Revision ID: 4eb346d9b5ce
Revises: 8d9287d3de49
Create Date: 2025-11-26 13:23:20.729480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb346d9b5ce'
down_revision = '8d9287d3de49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('industry_description')

    # ### end Alembic commands ###
