"""Add Ghost CMS integration fields

Revision ID: 4fc4c8941ac9
Revises: 2a3ec0fcac5c
Create Date: 2026-03-06 10:57:42.232412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc4c8941ac9'
down_revision = '2a3ec0fcac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pushed_to_ghost', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ghost_post_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('ghost_post_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ghost_pushed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pushed_to_ghost', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ghost_post_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('ghost_post_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ghost_pushed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ghost_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ghost_admin_api_key', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ghost_newsletter_slug', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('ghost_newsletter_slug')
        batch_op.drop_column('ghost_admin_api_key')
        batch_op.drop_column('ghost_url')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('ghost_pushed_at')
        batch_op.drop_column('ghost_post_url')
        batch_op.drop_column('ghost_post_id')
        batch_op.drop_column('pushed_to_ghost')

    with op.batch_alter_table('content_version', schema=None) as batch_op:
        batch_op.drop_column('ghost_pushed_at')
        batch_op.drop_column('ghost_post_url')
        batch_op.drop_column('ghost_post_id')
        batch_op.drop_column('pushed_to_ghost')

    # ### end Alembic commands ###
