"""Add reader_personas and reader_pain_points to Publication

Revision ID: 5746e7c56f26
Revises: 4eb346d9b5ce
Create Date: 2025-11-30 13:26:11.505645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5746e7c56f26'
down_revision = '4eb346d9b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_personas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reader_pain_points', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('reader_pain_points')
        batch_op.drop_column('reader_personas')

    # ### end Alembic commands ###
