"""Add keywords field to NewsContent and change source_url to Text

Revision ID: 5f68985c0979
Revises: f982a5085390
Create Date: 2025-12-08 09:51:51.490649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f68985c0979'
down_revision = 'f982a5085390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.Text(), nullable=True))
        batch_op.alter_column('source_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.alter_column('source_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
