"""Add AuthorProfile model

Revision ID: 728d6d9668d6
Revises: 21478fb15e00
Create Date: 2026-04-14 10:01:56.666224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728d6d9668d6'
down_revision = '21478fb15e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('style_guide', sa.Text(), nullable=True),
    sa.Column('sample_articles', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_profile_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_profile_publication_id'))

    op.drop_table('author_profile')
    # ### end Alembic commands ###
