"""Add notes field to NewsContent

Revision ID: 77167ff5edba
Revises: 5f68985c0979
Create Date: 2025-12-14 09:32:27.118160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77167ff5edba'
down_revision = '5f68985c0979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
