"""Add deck and teaser fields to NewsContent

Revision ID: 796112e94e5d
Revises: a71dbf23155e
Create Date: 2025-12-18 19:54:31.379935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796112e94e5d'
down_revision = 'a71dbf23155e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teaser', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.drop_column('teaser')
        batch_op.drop_column('deck')

    # ### end Alembic commands ###
