"""Add scheduling fields to Publication

Revision ID: b25c0d95bb3a
Revises: 409e0f5948d4
Create Date: 2026-01-06 13:59:01.165267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25c0d95bb3a'
down_revision = '409e0f5948d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('schedule_frequency', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('schedule_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('schedule_day_of_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_scheduled_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_scheduled_run', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_publication_next_scheduled_run'), ['next_scheduled_run'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_next_scheduled_run'))
        batch_op.drop_column('next_scheduled_run')
        batch_op.drop_column('last_scheduled_run')
        batch_op.drop_column('schedule_day_of_week')
        batch_op.drop_column('schedule_time')
        batch_op.drop_column('schedule_frequency')
        batch_op.drop_column('schedule_enabled')

    # ### end Alembic commands ###
