"""Add ContentVersion model for multi-AI versions

Revision ID: b508495a6192
Revises: b25c0d95bb3a
Create Date: 2026-01-21 10:42:00.390344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b508495a6192'
down_revision = 'b25c0d95bb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('ai_provider', sa.String(length=32), nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('deck', sa.Text(), nullable=True),
    sa.Column('teaser', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pushed_to_cms', sa.Boolean(), nullable=True),
    sa.Column('cms_id', sa.String(length=128), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('pushed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['news_content.id'], ),
    sa.ForeignKeyConstraint(['pushed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_version_content_id'), ['content_id'], unique=False)

    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'content_version', ['selected_version_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('selected_version_id')

    with op.batch_alter_table('content_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_version_content_id'))

    op.drop_table('content_version')
    # ### end Alembic commands ###
