"""Add is_final field to ContentVersion

Revision ID: c3a6aee02773
Revises: b508495a6192
Create Date: 2026-01-27 08:09:31.805815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a6aee02773'
down_revision = 'b508495a6192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_final', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_version', schema=None) as batch_op:
        batch_op.drop_column('is_final')

    # ### end Alembic commands ###
