"""Add WorkflowRun model

Revision ID: cee4fb940186
Revises: 796112e94e5d
Create Date: 2025-12-21 12:40:18.979570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee4fb940186'
down_revision = '796112e94e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('workflow_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_run_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_run_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_run_created_at'))

    op.drop_table('workflow_run')
    # ### end Alembic commands ###
