"""Add CandidateArticle model and publication research fields


Revision ID: e506ffefb5b6
Revises: d7a8f92c1e34
Create Date: 2026-02-18 08:15:33.005727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e506ffefb5b6'
down_revision = 'd7a8f92c1e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('news_source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('source_weight', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('news_content_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_content_id'], ['news_content.id'], ),
    sa.ForeignKeyConstraint(['news_source_id'], ['news_source.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'url_hash', name='uq_candidate_pub_url')
    )
    with op.batch_alter_table('candidate_article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_article_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_article_news_source_id'), ['news_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_article_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_article_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_article_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_article_url_hash'), ['url_hash'], unique=False)

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_research_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('require_candidate_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('require_candidate_review')
        batch_op.drop_column('last_research_run')

    with op.batch_alter_table('candidate_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_article_url_hash'))
        batch_op.drop_index(batch_op.f('ix_candidate_article_status'))
        batch_op.drop_index(batch_op.f('ix_candidate_article_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_candidate_article_publication_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_article_news_source_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_article_discovered_at'))

    op.drop_table('candidate_article')
    # ### end Alembic commands ###
