"""Add ResearchLog model for pipeline error tracking

Revision ID: f5dc935706df
Revises: 2f1ce09bbcb6
Create Date: 2026-04-08 08:17:29.066227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dc935706df'
down_revision = '2f1ce09bbcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('news_source_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_source_id'], ['news_source.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_log_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_log_news_source_id'), ['news_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_log_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_log_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_log_publication_id'))
        batch_op.drop_index(batch_op.f('ix_research_log_phase'))
        batch_op.drop_index(batch_op.f('ix_research_log_news_source_id'))
        batch_op.drop_index(batch_op.f('ix_research_log_level'))
        batch_op.drop_index(batch_op.f('ix_research_log_created_at'))

    op.drop_table('research_log')
    # ### end Alembic commands ###
