"""Add keywords field to NewsSource

Revision ID: f982a5085390
Revises: 10f8fbee029e
Create Date: 2025-12-01 09:29:47.739123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f982a5085390'
down_revision = '10f8fbee029e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_source', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
